# -*- coding: utf-8 -*-

"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        tmp = ord(t[-1])
        for i in range(len(s)):
            tmp = tmp ^ ord(s[i]) ^ ord(t[i])
        return chr(tmp)
